/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { Inter } from "next/font/google";
import useFetch from "@/hooks/useFetch";
import { Button, Col, Container, Row } from "react-bootstrap";
import { BiSolidCalendar } from "react-icons/bi";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Notice() {
  const { data, loading } = useFetch("/notice/Upcoming");

  //   Convert Date
  const formatDateString = (inputDate) => {
    const options = { year: "numeric", month: "short", day: "numeric" };
    const formattedDate = new Date(inputDate).toLocaleDateString(
      undefined,
      options
    );
    return formattedDate;
  };

  return (
    <>
      <Head>
        <title>Dhaka University Chemistry Alumni Association Upcoming</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.jpeg" />
      </Head>
      <main>
        {loading ? (
          <div className="loadingContainer">
            <img src="./loading.gif" alt="" className="loadingGif" />
          </div>
        ) : (
          <>
            {/* Notice Title */}
            <div className="headerTitle mt-2">
              <h3 class="headerTitleMain">Upcoming Events</h3>
            </div>
            {/* Notice Details */}
            <Container className="mt-0">
              <Row className="mb-4">
                {data?.data?.map((item) => {
                  return (
                    <Col
                      lg={10}
                      md={10}
                      sm={12}
                      className="mx-auto"
                      key={item?.serial}
                    >
                      <h3 style={{ fontSize: "20px", fontWeight: "bold" }}>
                        {item?.title}
                      </h3>
                      <div className="d-flex align-items-center">
                        <BiSolidCalendar
                          style={{
                            fontSize: "20px",
                            color: "rgb(255, 198, 0)",
                          }}
                        />
                        <span className="ms-1">
                          Published on: {formatDateString(item?.date)}
                        </span>
                      </div>
                      <Link href={`/upcomingEvent/${item?.id}`}>
                        <Button
                          style={{
                            background: "rgb(255, 198, 0)",
                            border: "1px solid rgb(255, 198, 0)",
                            fontWeight: "bold",
                            padding: "4px 15px",
                            marginTop: "15px",
                          }}
                        >
                          View Details
                        </Button>
                      </Link>
                      <hr />
                    </Col>
                  );
                })}
              </Row>
            </Container>
          </>
        )}
      </main>
    </>
  );
}
